---
# Redhat based OS
- name: Rundeck | get rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | get rundeck rpm
  yum:
    name: rundeck
    state: present
  become: yes
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | get installed / targeting version
  shell: "yum info rundeck | grep 'Version' | awk '{print $3}'"
  become: yes
  register: rundeck_targeting_version
  tags:
    - rundeck
    - install
    - packages
